name: Cypress Daily Test Run

on:
  schedule:
    - cron: '0 4 * * *'  # Runs every day at 4am
  workflow_dispatch:    

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Run 2 parallel instances. Adjust based on number of specs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests (Parallel with Recording)
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          group: 'Daily Parallel Run'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
